# Generated by Django 4.0.2 on 2022-11-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
