# Generated by Django 4.0.2 on 2022-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ide_link',
            field=models.URLField(null=True),
        ),
    ]
