# Generated by Django 4.0.2 on 2022-11-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_ide_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem_difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_statement',
            new_name='statement',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='problem_id',
        ),
    ]
