# Generated by Django 4.0.2 on 2022-11-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_rename_problem_difficulty_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='statement',
        ),
    ]
