# Generated by Django 4.0.2 on 2022-11-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_remove_problem_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
