# Generated by Django 4.0.2 on 2022-11-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_alter_interview_name_alter_problem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='name',
        ),
    ]
