# Generated by Django 4.0.2 on 2022-11-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_alter_interview_viewee_alter_interview_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer',
            name='evalForm',
        ),
        migrations.RemoveField(
            model_name='interviewer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interviewee',
        ),
        migrations.DeleteModel(
            name='Interviewer',
        ),
    ]
