# Generated by Django 4.0.2 on 2022-11-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_and_message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='sender',
        ),
    ]
