# Generated by Django 4.0.2 on 2022-11-29 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend_and_message', '0003_friendship_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
