# Generated by Django 4.0.2 on 2022-11-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend_and_message', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='friendship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='friend_and_message.friendship'),
        ),
    ]
