# Generated by Django 4.0.2 on 2022-11-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_and_message', '0008_message_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='friendship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
