# Generated by Django 4.0.2 on 2022-11-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_and_message', '0009_alter_message_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='friendship',
        ),
        migrations.AddField(
            model_name='message',
            name='friendship1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to=settings.AUTH_USER_MODEL),
        ),
    ]
