# Generated by Django 4.0.2 on 2022-11-29 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_and_message', '0010_remove_message_friendship_message_friendship1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='friendship1',
        ),
        migrations.AddField(
            model_name='message',
            name='friendship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
