# Generated by Django 4.0.2 on 2022-11-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend_and_message', '0011_remove_message_friendship1_message_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='friendship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='friend_and_message.friendship'),
        ),
    ]
