# Generated by Django 4.0.2 on 2022-11-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_calender_calendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='', max_length=3)),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='calendar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.availability'),
        ),
    ]
