# Generated by Django 4.0.2 on 2022-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_role',
            field=models.CharField(choices=[('B', 'Both'), ('ER', 'Interviewer'), ('EE', 'Interviewee')], default='', max_length=2),
        ),
    ]
