# Generated by Django 4.0.2 on 2022-11-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_preferred_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='history',
        ),
    ]
