# Generated by Django 4.0.2 on 2022-11-20 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
