# Generated by Django 4.0.2 on 2022-11-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_calendar_alter_historyitem_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyitem',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
