# Generated by Django 4.0.2 on 2022-11-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_historyitem_link_todoitem_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='link',
        ),
    ]
